version: "3.3"

services:
  frontend:
    build: frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    env_file: ./backend/.env
